--- 
- hosts: all
  tasks:
    
    - include_tasks: cosas/instalacion.yml
    - include_tasks: cosas/configurar_ssh.yml
    - include_tasks: cosas/configurar_usuarios.yml

  become: true
  become_user: root
