---

  #- name: Copiar archivo de credenciales de mysql
    #ansible.builtin.copy:
      #src: cosas/.my.cnf
      #dest: /root

  - name: Iniciar servicio   
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: mysqld 
    
  - name: leer log de MySql
    ansible.builtin.shell:
      cmd: cat /var/log/mysqld.log | grep "A temporary password"
    register: log_mysql

  - set_fact:
      log_var: "{{ log_mysql.stdout | regex_search('(?<=: )(.*)$') }}"

  - name: mostrar a ver
    debug:
      var: log_var

  - name: Cambiar contraseña para root usando la contraseña temporal
    shell: mysql -e "SET PASSWORD = PASSWORD('20jCloquitolocoloco#++++');" --connect-expired-password -u root -p"{{ log_var }}"
    ignore_errors: yes

  - name: Copiar dump de la base de datos
    ansible.builtin.copy:
      src: cosas/MySqlDump.sql
      dest: /tmp
  
  - name: Importar base de datos
    community.mysql.mysql_db:
      login_user: root
      login_password: 20jCloquitolocoloco#++++ 
      name: codelaw
      state: import
      target: /tmp/MySqlDump.sql

  - name: Crear usuario para la ejecucion de los triggers, (el que aparece como definer en el mysqldump)
    community.mysql.mysql_user:
      login_user: root
      login_password: 20jCloquitolocoloco#++++
      state: present
      name: diego.ibanez
      password: fraganciadesomunal
      priv: "*.*:ALL,GRANT"
