---
  - name: desactivar SElinux
    ansible.posix.selinux:
      state: disabled

  - name: Cambiar puerto de SSH a 24153
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#Port\ 22'
      line: Port 24153
 
  - name: Agregar exlusion del firewall al puerto 24153
    ansible.posix.firewalld:
      port: 24153/tcp
      permanent: yes
      immediate: yes
      state: enabled
  
  - name: Deshabilitar el uso de root a traves de SSH
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin\ yes'
      line: PermitRootLogin no

  - name: Desactivar inicio por contraseña en SSH
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication\ yes'
      line: PasswordAuthentication no

  - name: Desactivar esa cosa que rompe los huevos
    ansible.builtin.lineinfile:
      path: /etc/ssh/ssh_config
      regexp: '^#   StrictHostKeyChecking'
      line: StrictHostKeyChecking no

  - name: Restringir SSH a determinados usuarios
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: AllowUsers admin
    
  - name: reiniciar ssh
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: sshd
